config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :task_lists do
    put :set_public
    put :set_private
    put :create_task
    resources :tasks, only: %i[set_done set_undone destroy] do
      put :set_done
      put :set_undone
    end
  end
  resources :favorites, only: %i[index create destroy]
  get '/discovery', to: 'task_lists#discovery'
  root to: 'task_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :task_list
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list

  enum status: { open: 0, closed: 5 }

  validates :description, presence: { message: 'Descrição não pode ficar em branco' }
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc { |att| att['description'].blank? }

  enum status: { personal: 0, shareable: 5 }

  validates :name, presence: { message: 'Nome não pode ficar em branco' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :task_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: { message: 'Nome não pode ficar em branco' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
                             .map(&:task_list)
  end

  def create
    @favorite = Favorite.create(task_list_id: params[:task_list_id])
    @favorite.user = current_user
    @favorite.save
    flash[:notice] = 'Lista favoritada!'
    redirect_to task_list_path(@favorite.task_list)
  end

  def destroy
    @favorite = Favorite.find_by(task_list_id: params[:task_list_id], user_id: current_user.id)
    @favorite.destroy
    flash[:alert] = 'Lista desfavoritada!'
    redirect_back(fallback_location: task_list_path(params[:task_list_id]))
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :find_favorites, only: %i[show discovery]
  before_action :set_task_list, only: %i[update destroy]
  before_action :set_task_list_id, only: %i[create_task set_public set_private]

  def index
    @task_lists = current_user.task_lists.order(created_at: :desc)
  end

  def show
    if !check_user?
      flash[:alert] = 'Você não tem acesso a esta lista!'
      redirect_to root_path
    else
      return @task_list, @favorites_ids
    end
  end

  def new
    @task_list = TaskList.new
    @task_list.tasks.build
  end

  def create
    @task_list = TaskList.new(task_list_params)
    @task_list.user = current_user
    if @task_list.save
      flash[:notice] = 'Lista criada!'
      redirect_to @task_list
    else
      render :new
    end
  end

  def edit
    if !check_user?
      flash[:alert] = 'Você não tem acesso a esta lista!'
      redirect_to root_path
    else
      return @task_list
    end
  end

  def update
    if @task_list.update(task_list_params)
			redirect_to @task_list
		else
			render :edit
		end
  end

  def destroy
		@task_list.destroy
		redirect_to task_lists_path
	end

  def create_task
    @task_list.update(task_list_params)
    redirect_to @task_list
  end

  def discovery
    @task_lists = TaskList.where(status: :shareable)
                          .where.not(user_id: current_user.id)
                          .order(created_at: :desc)
  end

  def set_public
    @task_list.update(status: :shareable)
    flash[:alert] = "'#{@task_list.name}' agora é pública"
    redirect_to task_list_path(@task_list)
  end

  def set_private
    @task_list.update(status: :personal)
    flash[:alert] = "'#{@task_list.name}' agora é privada"
    redirect_to task_list_path(@task_list)
  end

  private

    def check_user?
      @task_list = TaskList.find(params[:id])
      (@task_list.user == current_user || @task_list.shareable?) ? true : false
    end

    def find_favorites
      @favorites = current_user.favorites.map(&:task_list)
      @favorites_ids = []
      @favorites.each { |item| @favorites_ids << item.id }
      return @favorites_ids
    end

    def task_list_params
      params.require(:task_list).permit(:name, :status, tasks_attributes: [:id, :description])
    end

    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    def set_task_list_id
      @task_list = TaskList.find(params[:task_list_id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def set_done
    @task = Task.find(params[:task_id])
    @task.update(status: :closed)
    flash[:alert] = "'#{@task.description}' marcada como feita"
    redirect_to task_list_path(@task.task_list)
  end

  def set_undone
    @task = Task.find(params[:task_id])
    @task.update(status: :open)
    flash[:alert] = "'#{@task.description}' desmarcada como feita"
    redirect_to task_list_path(@task.task_list)
  end

  def destroy
    @task = Task.find(params[:id])
		@task.destroy
		redirect_to edit_task_list_path(params[:task_list_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association, **args)
    #cria um novo objeto da associação (:tasks)
    new_object = f.object.send(association).klass.new

    #pega o id do objeto criado
    id = new_object.object_id

    #cria os campos do formulário
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    #passa o link para o formulário
    link_to(name, '#', class: 'add_fields ' + args[:class], data:{id: id, fields: fields.gsub("\n","")})
  end
end

app/views/favorites/index.html.erb
<div class="container">
  <h1 class='display-4 my-5'>Listas Favoritas</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Usuário</th>
      </tr>
    </thead>
    <tbody>
      <% @favorites.each do |favorite|  %>
          <tr>
              <td><%= link_to favorite.name, task_list_path(favorite) %></td>
              <td>
                <%= favorite.user.name %>
              </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoSeg ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to 'AutoSeg ToDo', '/', class: 'navbar-brand d-inline-block align-top' %>
      <div class="collapse navbar-collapse">
        <% if current_user %>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active my-auto mx-3 item-nav">
              <%= link_to 'Minhas Listas', root_path %>
            </li>
            <li class="nav-item active my-auto mx-3 item-nav">
              <%= link_to 'Listas Favoritas', favorites_path %>
            </li>
            <li class="nav-item active my-auto mx-3 item-nav">
              <%= link_to 'Descobrir Listas', discovery_path %>
            </li>
          </ul>
        </div>
        <div class="dropdown-divider"></div>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class:"btn btn-outline-light" %>
      <% end %>
    </nav>

    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= alert %></strong>
      </div>
    <% elsif notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong><%= notice %></strong>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/task_lists/_task_fields.html.erb
<div class="form-group row task-input">
  <%= f.label :description, 'Tarefa:', class:"col-sm-2 mb-3" %>
  <%= f.text_field :description, class:"form-control col-sm-8" %>
  <%= f.hidden_field :_destroy, class: "remove" %>
  <a href="" class="delete-input btn btn-outline-danger col-sm-2" type="button" >Deletar</a>
</div>

app/views/task_lists/discovery.html.erb
<div class="container">
  <h1 class='display-4 my-5'>Descobrir Listas</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Usuário</th>
        <th scope="col">Favorita</th>
      </tr>
    </thead>
    <tbody>
      <% @task_lists.each do |task_list|  %>
          <tr>
              <td><%= link_to task_list.name, task_list_path(task_list) %></td>
              <td><%= task_list.user.name %></td>
              <td>
                <% if @favorites_ids.include?(task_list.id) %>
                  <span class='text-primary'>Sim</span>
                <% else %>
                  <span class='text-dark'>Não</span>
                <% end %>
              </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/task_lists/edit.html.erb
<div class="container">
  <div class="row row-cols-2 my-5">
    <div class="col-8">
      <h1 class="display-4"><%= @task_list.name %></h1>
    </div>
    <div class="col-4">
      <%= link_to 'Deletar Lista', task_list_path(@task_list), method: :delete, class: "btn btn-danger", data: { confirm: 'Quer apagar esta lista?' } %>
    </div>
  </div>

  <%= form_with model: @task_list do |form| %>
    <div class="form-group row form-check">
      <%= form.label(:status, "Privada") %>
      <%= form.radio_button(:status, :personal, checked: true, class:'mr-3') %>
      <%= form.label(:status, "Pública") %>
      <%= form.radio_button(:status, :shareable) %>
    </div>
    <div class="form-group row">
      <%= form.label :name, 'Nome:', class:"col-sm-2" %>
      <%= form.text_field :name, class:"form-control col-sm-10" %>
    </div>

    <table class="table mt-5">
      <thead class="thead">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Deletar</th>
        </tr>
      </thead>
      <tbody>
        <% @task_list.tasks.order(created_at: :desc).each do |task|  %>
            <tr>
                <td><%= task.description %></td>
                <td><%= link_to 'Deletar tarefa', task_list_task_path(@task_list, task), method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Quer apagar esta tarefa?' } %></td>
            </tr>
        <% end %>
      </tbody>
    </table>

    <div class="form-group row">
      <div class="col-sm-5">
          <%= form.submit 'Salvar', class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

  <div class="col-sm-10">
      <% if @task_list.errors.any?%>
          <p>Você deve corrigir os erros para continuar:</p>
          <% @task_list.errors.full_messages.each do |message|  %>
              <p><%= message %></p>
          <% end %>
      <% end %>
  </div>

  <%= link_to 'Voltar', task_list_path(@task_list), class:"btn btn-outline-dark mb-5" %>
</div>

app/views/task_lists/index.html.erb
<div class="container">
  <div class="row row-cols-2 my-5">
    <div class="col-8">
      <h1 class='display-4'>Minhas Listas</h1>
    </div>
    <div class="col-2">
      <%= link_to '+ Nova Lista', new_task_list_path, class:"btn btn-success" %>
    </div>
  </div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Visibilidade</th>
      </tr>
    </thead>
    <tbody>
      <% @task_lists.each do |task_list|  %>
          <tr>
              <td><%= link_to task_list.name, task_list_path(task_list) %></td>
              <td>
                <% if task_list.personal? %>
                  <span class='text-danger'>Privada</span>
                <% elsif task_list.shareable? %>
                  <span class='text-info'>Pública</span>
                <% end %>
              </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/task_lists/new.html.erb
<div class="container">
  <h1 class="display-4 my-5">Nova Lista</h1>

  <%= form_with model: @task_list do |form| %>
    <div class="form-group row form-check">
      <%= form.label(:status, "Privada") %>
      <%= form.radio_button(:status, :personal, checked: true, class:'mr-3') %>
      <%= form.label(:status, "Pública") %>
      <%= form.radio_button(:status, :shareable) %>
    </div>
    <div class="form-group row">
      <%= form.label :name, 'Nome:', class:"col-sm-2" %>
      <%= form.text_field :name, class:"form-control col-sm-10" %>
    </div>
    <%= form.fields_for :tasks do |f| %>
      <%#= render 'task_fields', f: f %>
    <% end %>
    <%= link_to_add_fields('Nova tarefa', form, :tasks, class: "btn btn-primary") %>
    <div class="form-group row mt-3">
      <div class="col-sm-5">
          <%= form.submit 'Salvar', class: "btn btn-success" %>
          <%= link_to 'Voltar', task_lists_path, class:"btn btn-outline-dark" %>
      </div>
    </div>
  <% end %>

  <div class="col-sm-10">
      <% if @task_list.errors.any?%>
          <p>Você deve corrigir os erros para continuar:</p>
          <% @task_list.errors.full_messages.each do |message|  %>
              <p><%= message %></p>
          <% end %>
      <% end %>
  </div>
</div>

app/views/task_lists/show.html.erb
<div class="container">
  <div class="row row-cols-4 my-4">
    <div class="col-6">
      <h1 class='display-4'><%= @task_list.name %></h1>
    </div>

    <div class="col-2 mt-3">
      <% if @task_list.shareable? && @task_list.user != current_user %>
        <% unless @favorites_ids.include?(@task_list.id) %>
          <%= form_with(url: '/favorites', method: :create) do %>
            <%= hidden_field_tag :task_list_id, @task_list.id %>
            <%= submit_tag("Favoritar", class: "btn btn-warning") %>
          <% end %>
        <% else %>
          <%= form_with(url: favorite_path, method: :delete) do %>
            <%= hidden_field_tag :task_list_id, @task_list.id %>
            <%= submit_tag("Desfavoritar", class: "btn btn-danger") %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="col-2 mt-3">
      <% if @task_list.shareable? && @task_list.user == current_user %>
        <%= form_with(url: task_list_set_private_path(@task_list.id), method: :put) do %>
          <%= hidden_field_tag :status, :personal %>
          <%= submit_tag("Tornar privada", class: "btn btn-warning") %>
        <% end %>
      <% elsif @task_list.personal? %>
        <%= form_with(url: task_list_set_public_path(@task_list.id), method: :put) do %>
          <%= hidden_field_tag :status, :shareable %>
          <%= submit_tag("Tornar pública", class: "btn btn-danger") %>
        <% end %>
      <% end %>
    </div>

    <div class="col-2 mt-3">
      <% if @task_list.user == current_user %>
        <%= link_to 'Editar Lista', edit_task_list_path(@task_list), class:"btn btn-warning" %>
      <% end %>
    </div>
  </div>


  <% if @task_list.user == current_user %>
    <%= form_with(model: @task_list, url: task_list_create_task_path(@task_list.id), method: :put) do |form| %>
      <%= form.fields_for :tasks do |f| %>
      <% end %>
      <div class="form-group row mt-3">
        <div class="col-sm-9">
          <%= link_to_add_fields('+ Nova tarefa', form, :tasks, class: "btn btn-info add-task") %>
          <%= form.submit 'Salvar', class: "btn btn-success submit-task" %>
        </div>
      </div>
    <% end %>
  <% end %>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Tarefas</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @task_list.tasks.order(created_at: :desc).each do |task| %>
        <tr>
          <td>
            <% if task.open? %>
              <%= task.description %>
            <% else %>
              <del><%= task.description %></del>
            <% end %>
          </td>
          <td>
            <% if task.open? && @task_list.user == current_user %>
              <%= form_with(url: task_list_task_set_done_path(@task_list.id,task.id), method: :put) do %>
                <%= hidden_field_tag :status, :closed %>
                <%= submit_tag("Feito", class: "btn btn-success", id: "set-done-#{task.id}") %>
              <% end %>
            <% elsif task.closed? && @task_list.user == current_user %>
              <%= form_with(url: task_list_task_set_undone_path(@task_list.id,task.id), method: :put) do %>
                <%= hidden_field_tag :status, :open %>
                <%= submit_tag("Desfazer", class: "btn btn-warning", id: "set-undone-#{task.id}") %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="col-sm-5 mt-5">
    <%= link_to 'Voltar', task_lists_path, class:"btn btn-outline-dark" %>
  </div>
</div>